[package]
name = "solana-feature-set"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
lazy_static = { workspace = true }
solana-clock = { workspace = true }
solana-epoch-schedule = { workspace = true }
solana-hash = { workspace = true }
solana-pubkey = { workspace = true }
solana-sdk-macro = { workspace = true }
solana-stake-history = { workspace = true }
thiserror = { workspace = true }
