[package]
name = "solana-entrypoint-consts"
description = "Solana entrypoint constants"
documentation = "https://docs.rs/solana-entrypoint-consts"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
