[package]
name = "solana-secp256k1-recover"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
borsh = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[target.'cfg(target_os = "solana")'.dependencies]
solana-syscall-core = { workspace = true }

[target.'cfg(not(target_os = "solana"))'.dependencies]
libsecp256k1 = { workspace = true }
