[package]
name = "solana-program-utils"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
serde = { workspace = true }
solana-instruction = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
solana-system-instruction-core = { workspace = true }
