[package]
name = "solana-message"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
blake3 = { workspace = true }
lazy_static = { workspace = true }
serde = { workspace = true, features = ["derive"] }
solana-address-lookup-table-core = { workspace = true }
solana-hash = { workspace = true }
solana-instruction = { workspace = true }
solana-native-programs = { workspace = true }
solana-nonce-core = { workspace = true }
solana-program-utils = { workspace = true }
solana-pubkey = { workspace = true }
solana-sanitize = { workspace = true }
solana-short-vec = { workspace = true }
solana-system-instruction-core = { workspace = true }
solana-sysvar-core = { workspace = true }
solana-wasm-bindgen = { workspace = true }
thiserror = { workspace = true }
wasm-bindgen = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
bitflags = { workspace = true }
itertools = { workspace = true }
solana-msg-and-friends = { workspace = true }
