[package]
name = "solana-msg-and-friends"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
num-traits = { workspace = true }
rustversion = { workspace = true }
serde = { workspace = true, features = ["derive"] }
solana-clock = { workspace = true }
solana-decode-error = { workspace = true }
solana-instruction = { workspace = true }
solana-pubkey = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(target_os = "solana")'.dependencies]
solana-syscall-core = { workspace = true }
