[package]
name = "solana-signature-core"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bs58 = { workspace = true }
ed25519-dalek = { workspace = true }
generic-array = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
solana-sanitize = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
curve25519-dalek = { workspace = true }
solana-pubkey = { workspace = true }
