[package]
name = "solana-transaction-error"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true, features = ["derive"] }
solana-instruction = { workspace = true }
solana-message = { workspace = true }
solana-sanitize = { workspace = true }
thiserror = { workspace = true }
