[package]
name = "solana-instruction"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
borsh = { workspace = true }
num-traits ={ workspace = true }
serde = { workspace = true, features = ["derive"] }
solana-pubkey = { workspace = true }
solana-sanitize = { workspace = true }
solana-short-vec = { workspace = true }
solana-syscall-core = { workspace = true }
solana-wasm-bindgen = { workspace = true }
thiserror = { workspace = true }
wasm-bindgen = { workspace = true }
