[package]
name = "solana-slot-history"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bv = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
solana-clock = { workspace = true }
