[package]
name = "solana-keccak"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
borsh = { workspace = true }
bs58 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sha3 = { workspace = true }
solana-atomic-u64 = { workspace = true }
solana-sanitize = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(target_os = "solana")'.dependencies]
solana-syscall-core = { workspace = true }
