[package]
name = "solana-short-vec"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
serde_json = { workspace = true }
