[package]
name = "solana-message-error"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
solana-sanitize = { workspace = true }
thiserror = { workspace = true }
