[package]
name = "solana-poseidon-syscall-error"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
light-poseidon = { workspace = true }
thiserror = { workspace = true }
