[package]
name = "solana-program-utils-sdk"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true }
solana-consts = { workspace = true }
solana-instruction = { workspace = true }
solana-program-utils = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
serde = { workspace = true, features = ["derive"] }
